/* Copyright (c) 2021-2026 Richard Rodger, MIT License */

// Generated by ../embed-translate.js. Edit tabnas.plugin.json or alchemy/*,
// then run npm run embed.

type TranslationPart = Readonly<{
  entry: string
  source?: string
}>

type TranslationParts = Readonly<{
  manifest: string
  lift?: TranslationPart
  embed?: TranslationPart
  render?: TranslationPart
}>

const TRANSLATION: TranslationParts = Object.freeze({
  manifest: `{
  "$schema": "https://tabnas.dev/schema/plugin.schema.json",
  "name": "@tabnas/markdown",
  "go": "github.com/tabnas/markdown/go",
  "rust": "tabnas-markdown",
  "description": "CommonMark and GFM Markdown parsing for the tabnas engine.",
  "engine": "@tabnas/parser",
  "extensions": [
    ".md",
    ".markdown"
  ],
  "mediaTypes": [
    "text/markdown"
  ],
  "languageId": "markdown",
  "pluginKind": "grammar",
  "specDir": "test/spec",
  "clib": {
    "dir": "go/clib",
    "library": "libtabnasmarkdown",
    "abi": "v1",
    "errorCodes": [
      "usage",
      "grammar",
      "handle",
      "internal"
    ]
  },
  "errorCodes": [],
  "docs": "https://tabnas.dev/docs/packages",
  "repository": "https://github.com/tabnas/markdown",
  "versionSource": "ts/package.json",
  "translate": {
    "reads": [
      "records",
      "tree"
    ],
    "writes": "records",
    "root": "array",
    "schema": "mdast",
    "lift": "alchemy/lift.alc",
    "render": "alchemy/render.alc",
    "loss": [
      "The rows are the elements of the root array, and a root of another kind is written as one row.",
      "The columns are the first row's, an object's keys or an array's positions labelled 0, 1 and so on, so a member or position of a later row that the first row lacks is not written, and one the first row has and a later row lacks is an empty cell.",
      "When the first row is a scalar there is one column, named value, and every row is written whole in it, an array or an object as its compact JSON text.",
      "A table of no columns, such as the one an empty array or object makes, is written as the empty document, which reads back as the empty table.",
      "Read as records, a document with no table is the empty table, of no columns and no rows.",
      "Read as records, a document with several tables is its first table, and the tables after it are not read.",
      "Inline markup in a cell is flattened to its text when it is read, an image to its alt text, and a written cell is plain text, so text that spells inline markup reads back as that markup.",
      "A null and a missing cell are both written as an empty cell, so the two cannot be told apart, or from an empty string, when read back.",
      "A nested array or object in a cell is written as its compact JSON text.",
      "A number that is not finite is written as Infinity, -Infinity or NaN, and as null inside a nested array or object, since JSON has no spelling for one.",
      "Every value is written as text, so a number or a boolean reads back as a string.",
      "Column alignment is not kept.",
      "A line break in a cell is written as a space.",
      "Leading and trailing spaces in a cell are not kept.",
      "A U+0000 in a cell is written as it is, and the reader replaces it with U+FFFD when the table is read back."
    ]
  }
}
`,
  lift: Object.freeze({ entry: "markdown-lift", source: `; Markdown's lift: a document's events, as the reader builds them, read
; as a table's records: the TableRows protocol the standard library's
; \`table-from-json\` answers, one \`schema\`, a \`row\` per record and
; \`table-end\`. This is a library of definitions, each named
; \`markdown-...\`, which a host links with its own program (alchemy's
; \`compile_sources\`); its entry point is \`markdown-lift\`, and nothing
; else here is the host's to call.
;
; The reader's tree is mdast's shape: a \`document\` whose \`children\` are
; blocks, a \`table\` among them whose \`children\` are \`tableRow\`s of
; \`tableCell\`s, and each cell's \`children\` the inline nodes of its text:
; \`text\`, \`inlineCode\` and \`html\` with a \`value\`, \`image\` with an \`alt\`,
; and \`emphasis\`, \`strong\`, \`link\` and the rest with \`children\` of their
; own. \`type\` is each node's first member. The lift takes the first
; row's cells as the column labels and every later row as a record, and
; reads nothing else of the document: not the blocks around the table,
; and not the table's \`align\`. A cell is the text under it, every
; \`value\` and every image's \`alt\` in order, joined into one string
; (\`string-join\`, which alchemy has for this lift: \`concat\` and \`join\`
; answer a text, which a cell may not be), so inline markup is
; flattened to its text and an image to its alt text, and every cell is
; a string, as the CSV reader's records are: an empty cell is "", and a
; cell of text beside emphasis, a link, an image, inline HTML or an
; autolink is their texts run together, \`Bob *b*\` as \`Bob b\`.
;
; A Markdown document is read as records through its table and nothing
; else, so the first table is the one read: a table after it is not
; read, its rows and cells passed over as any other node's. A document
; with no table is read as the empty table, a schema of no columns, no
; row and \`table-end\`, which the render writes back as the empty
; document. The manifest's loss lines say both.
;
; The state is one vector, [stack phase seen in-cell runs cells]:
;   stack    the open containers, one marker each: \`:array\`, \`:node\` for
;            an object whose type is not known yet or is any other node,
;            and \`:table\`, \`:row\` or \`:cell\` once its \`type\` has named
;            one, or \`:later\` for a table after the first, so that its
;            end is known when its object ends;
;   phase    \`:before\` the table, \`:header\` inside it until its first
;            row ends, \`:body\` once the schema is written, \`:after\` it,
;            and \`:later\` inside a table after it, which is not read;
;   seen     what the last key was, \`:type\`, \`:text\` (a \`value\` or an
;            \`alt\`) or \`:other\`, so that the scalar after it is classified,
;            and \`:none\` before the first event, so that events with no
;            value at all are told from a document with no table;
;   in-cell  whether a cell is open, so that text under it is the cell's;
;   runs     the open cell's runs of text, in order;
;   cells    the open row's cells, as wide as one row.
; It grows with the document's nesting and with one row's width, never
; with the table's length or the document's: a row is emitted when its
; object ends and dropped, and a later table keeps nothing. Events no
; tree has (a key outside an object, an end with nothing open), and
; events of a node where the reader's tree never puts one (a row or a
; cell outside a table, a table inside one), fail with
; PROTOCOL_ORDER_ERROR, saying so.

; A column record of the TableRows protocol, as the standard library's
; \`public-column\` makes one.
def markdown-column [label]
  record
    entry :label label

; A cell's text: its runs, in order, as one string.
def markdown-cell-text [runs]
  string-join "" runs

; A \`value\` or an image's \`alt\` under a cell, which the reader's tree
; makes a string.
def markdown-run [value]
  match (kind value)
    case :string value
    case _ (fail "a node's value or alt under a table cell is not a string, which the reader's tree never has")

; What the scalar after a key is: the one after \`type\` names the node,
; the one after \`value\` (a text, code or HTML node's text) or \`alt\` (an
; image's alt text) is a run of text, any other is neither.
def markdown-seen [name]
  match name
    case "type" :type
    case "value" :text
    case "alt" :text
    case _ :other

; The top marker, or \`:none\` with nothing open.
def markdown-top [stack]
  match (count stack)
    case 0 :none
    case _ (top stack)

; The open object's marker, once its \`type\` has named it.
def markdown-mark [marker stack]
  push marker (pop stack)

; The scalar after \`type\`: the three nodes the lift reads leave their
; marker on the stack and move the phase; a table after the first leaves
; \`:later\`, and its rows and cells, like any other node, stay \`:node\`.
def markdown-node [name stack phase in-cell runs cells]
  match name
    case "table"
      match phase
        case :before (transition [(markdown-mark :table stack) :header :other in-cell runs cells] [])
        case :after (transition [(markdown-mark :later stack) :later :other in-cell runs cells] [])
        case _ (fail :protocol-order "the events hold a table inside a table, which the reader's tree never has")
    case "tableRow"
      match phase
        case :before (fail :protocol-order "the events hold a table row outside a table, which the reader's tree never has")
        case :after (fail :protocol-order "the events hold a table row outside a table, which the reader's tree never has")
        case :later (transition [stack phase :other in-cell runs cells] [])
        case _ (transition [(markdown-mark :row stack) phase :other in-cell runs []] [])
    case "tableCell"
      match phase
        case :before (fail :protocol-order "the events hold a table cell outside a table, which the reader's tree never has")
        case :after (fail :protocol-order "the events hold a table cell outside a table, which the reader's tree never has")
        case :later (transition [stack phase :other in-cell runs cells] [])
        case _
          if in-cell
            fail :protocol-order "the events hold a table cell inside a cell, which the reader's tree never has"
            transition [(markdown-mark :cell stack) phase :other true [] cells] []
    case _ (transition [stack phase :other in-cell runs cells] [])

; An object's end: a cell joins its row, a row is the schema or a
; record, the table is done, a later table is passed over, and any other
; node is dropped.
def markdown-close [stack phase in-cell runs cells]
  match (markdown-top stack)
    case :cell
      transition [(pop stack) phase :other false [] (push (markdown-cell-text runs) cells)] []
    case :row
      match phase
        case :header
          transition [(pop stack) :body :other in-cell runs []] [(schema (map markdown-column cells))]
        case _
          transition [(pop stack) phase :other in-cell runs []] [(row cells)]
    case :table
      transition [(pop stack) :after :other in-cell runs cells] []
    case :later
      transition [(pop stack) :after :other in-cell runs cells] []
    case :node
      transition [(pop stack) phase :other in-cell runs cells] []
    case _ (fail :protocol-order "the events end an object that is not open, which a tree's never do")

def markdown-event [stack phase seen in-cell runs cells event]
  match event
    case object-start
      transition [(push :node stack) phase :other in-cell runs cells] []
    case array-start
      transition [(push :array stack) phase :other in-cell runs cells] []
    case (key name)
      match (markdown-top stack)
        case :none (fail :protocol-order "the events hold a key outside an object, which a tree's never do")
        case :array (fail :protocol-order "the events hold a key inside an array, which a tree's never do")
        case _ (transition [stack phase (markdown-seen name) in-cell runs cells] [])
    case (scalar value)
      match seen
        case :type (markdown-node value stack phase in-cell runs cells)
        case :text
          if in-cell
            transition [stack phase :other in-cell (push (markdown-run value) runs) cells] []
            transition [stack phase :other in-cell runs cells] []
        case _ (transition [stack phase :other in-cell runs cells] [])
    case object-end (markdown-close stack phase in-cell runs cells)
    case array-end
      match (markdown-top stack)
        case :array (transition [(pop stack) phase :other in-cell runs cells] [])
        case _ (fail :protocol-order "the events end an array that is not open, which a tree's never do")

def markdown-lift-step [s event]
  match s
    case [stack phase seen in-cell runs cells]
      markdown-event stack phase seen in-cell runs cells event

; What the end of the events adds once every container is closed: the
; table's end, or, for a document with no table, the empty table.
def markdown-lift-end [stack outputs]
  match (count stack)
    case 0 outputs
    case _ (fail :protocol-order "the events ended inside a container, which a tree's never do")

def markdown-lift-finish [s]
  match s
    case [stack phase seen in-cell runs cells]
      match seen
        case :none (fail :protocol-order "the events hold no value, where a tree's hold one")
        case _
          match phase
            case :after (markdown-lift-end stack [table-end])
            case :before (markdown-lift-end stack [(schema []) table-end])
            case _ (fail :protocol-order "the events ended inside a table, which a tree's never do")

; The lift: the document's events in, the table's records out.
def markdown-lift [input]
  scan-emit [[] :before :none false [] []] markdown-lift-step markdown-lift-finish (events input)
` }),
  render: Object.freeze({ entry: "markdown-render", source: `; Markdown's render: a table's records, the TableRows protocol (one
; \`schema\`, a \`row\` per record and \`table-end\`), written as one GFM pipe
; table. This is a library of definitions, each named \`markdown-...\`,
; which a host links with its own program (alchemy's \`compile_sources\`);
; its entry point is \`markdown-render\`, and nothing else here is the
; host's to call.
;
; The table is the header row, \`| Name | Age |\`, the delimiter row,
; \`| --- | --- |\`, and a row per record, each line ended by a line feed
; and every cell between \`| \` and \` |\`. A cell is its value's text as
; the CSV renderer writes it (\`scalar-text\`: a string as it is, a number
; by its lexeme, or by its word, \`Infinity\`, \`-Infinity\` or \`NaN\`, when
; it is not finite, a boolean by its name, null and a missing cell as
; nothing, a vector or a record as its compact JSON text), with every
; backslash doubled and every pipe escaped as \`\\|\`, which the reader
; turns back into the characters (the reader's split skips the byte
; after a backslash, so the pipe's escape holds only when a backslash
; before it is itself escaped), and every line break replaced by a
; space, since a row is one line. No other character is escaped: the
; render cannot look at one (alchemy has no character test), so a cell
; is plain text, and text that spells inline markup reads back as that
; markup. A U+0000 in a cell is written as it is for the same reason,
; and the reader replaces it with U+FFFD, as CommonMark asks of every
; reader; the loss declaration says so. Alignment is not written: every
; column's delimiter is \`---\`.
;
; A table of no columns, the one an empty array or object makes, has no
; pipe table, since a row needs at least one cell: it is written as the
; empty document, nothing at all, and so are its rows, which have no
; cells. The lift reads that document back as the empty table, of no
; columns and no rows.
;
; The state is one marker: \`:start\` before the schema, the schema's
; width (a number) while rows may follow, and \`:ended\` after
; \`table-end\`, so that a stream which breaks the protocol (a row before
; the schema, a second schema, a row of another width, anything after
; the end, no end) fails with PROTOCOL_ORDER_ERROR, saying so, rather
; than being written. The check is this file's rather than
; \`csv-table\`'s, whose refusals speak of CSV.

; What \`scalar-text\` reads: null and a missing cell are written as
; nothing, where the CSV renderer's \`csv-options\` map a missing cell to
; an error, and a number that is not finite as its word.
def markdown-options
  record
    entry :null-text ""
    entry :missing ""
    entry :non-finite :literal

; A cell's text, as it stands between the pipes.
def markdown-cell [cell]
  replace-text "\\r" " "
    replace-text "\\n" " "
      replace-text "\\r\\n" " "
        replace-text "|" "\\\\|"
          replace-text "\\\\" "\\\\\\\\"
            scalar-text markdown-options cell

def markdown-label [column]
  markdown-cell (get :label column)

; One row of the table, cells in order.
def markdown-line [cells]
  concat
    "| "
    join " | " cells
    " |\\n"

; The delimiter row under the header, one \`---\` per column.
def markdown-delimiter [width]
  concat
    repeat width "| --- "
    "|\\n"

; A record's line in a table \`width\` columns wide, or none in a table of
; no columns, which is written as the empty document.
def markdown-row [width cells]
  match width
    case 0 []
    case _ [(markdown-line (map markdown-cell cells))]

def markdown-render-step [s event]
  match event
    case (schema columns)
      match s
        case :start
          match (count columns)
            case 0 (transition 0 [])
            case _
              transition (count columns)
                vector
                  markdown-line (map markdown-label columns)
                  markdown-delimiter (count columns)
        case _ (fail :protocol-order "the events hold a second schema, where a table's hold one")
    case (row cells)
      match s
        case :start (fail :protocol-order "the events hold a row before the schema, which a table's never do")
        case :ended (fail :protocol-order "the events hold a row after table-end, which a table's never do")
        case _
          match (compare (count cells) s)
            case :equal (transition s (markdown-row s cells))
            case _ (fail :protocol-order "the events hold a row that is not as wide as the schema, which a table's never do")
    case table-end
      match s
        case :start (fail :protocol-order "the events end before the schema, which a table's never do")
        case :ended (fail :protocol-order "the events hold a second table-end, which a table's never do")
        case _ (transition :ended [])

def markdown-render-finish [s]
  match s
    case :ended []
    case :start (fail :protocol-order "the events hold no schema, where a table's hold one first")
    case _ (fail :protocol-order "the events ended before table-end, which a table's never do")

; The render: the table's records in, the pipe table's text out.
def markdown-render [input]
  join ""
    scan-emit :start markdown-render-step markdown-render-finish input
` })
})

function translate (): TranslationParts | undefined {
  return TRANSLATION
}

export {
  translate,
}

export type {
  TranslationPart,
  TranslationParts,
}
